Getting-started: fix spock command names
The guide used 'create-node' instead of 'node-create', etc--if you try this, Spock will complain:

```
ERROR: Cannot find key: create-node
Usage: spock.py <command>
  available commands:    install | validate | tune | node-create |
                         repset-create | repset-add-table | sub-create |
                         sub-add-repset | sub-show-status | sub-show-table |
                         sub-wait-for-sync | health-check | metrics-check
```